### ISSUE TITLE
Wordpress.org package outdated?

### ISSUE THREAD

**Issue by scheinercc** [DannyvanHolten/acf-gravityforms-add-on#30]
Hi there,

In the README is a link to the wordpress.org plugin page*, but there it says "Last updated: 2 years ago". The latest commits are from 2 months ago, though. Will this reflect in a new version on the wordpress.org plugin page eventually?

Thanks

*https://wordpress.org/plugins/acf-gravityforms-add-on/

**Comment by christiaanstijnen** [comment]
Thanks for maintaining this plugin. 

Could you create a new release so also the latest version could be loaded via composer?

**Comment by catgofire** [comment]
@markhowellsmead Are you still maintaining this? In 7c80141634f6ef0deec5b69dfd8cc3acbf27eb73 you bump the version to `1.2.3` in a couple places, but not for the `ACF_GF_FIELD_VERSION` constant nor in `composer.json`. If you're around to accept it I'll submit a PR for these changes, otherwise I'll just maintain a private mirror and make changes there.

**Comment by markhowellsmead** [comment]
@catgofire The version number is corrected by 5859346f6f99b09719b18bd7345cddebb159afda. composer.json doesn't contain a version number because of the recommendation at https://getcomposer.org/doc/04-schema.md#version.

@DannyvanHolten Can you add me (@markhowellsmead) as a maintainer at WordPress.org please?

**Comment by vyskoczilova** [comment]
@markhowellsmead plus one for this. If you can't get the answer from @DannyvanHolten you could write to plugin@wordpress.com and point them to this repo and ask for access there. I believe that it should be quite easy since you maintain the plugin.

(and I'm glad to confirm that 1.2.4 version is finally compatible with Survey rank field :)

**Comment by markhowellsmead** [comment]
Thanks @vyskoczilova. I have access now and will endeavour to merge in all the updates in July.

**Comment by EmSixTeen** [comment]
Just wondering if you'd an updated timeline on doing this?

**Comment by markhowellsmead** [comment]
Version 1.2.6 is now released.

**Comment by RupW** [comment]
Great, thank you!

Can you update the 'tested up to version' too easily please? I'm still seeing the 'This plugin hasn’t been tested with the latest 3 major releases of WordPress' warning at the top of the page. Hopefully that's just updating the comment in the file in SVN trunk rather than actually having to push a new release with the number updated (in which case I wouldn't bother)

**Comment by markhowellsmead** [comment]
I've bumped a security fix version number to make sure the readme is refreshed. Now showing tested to 5.6 in the repo.
